export const Users = [
	{
		id: 1,
		name: 'John',
		surname: 'mongoose',
		email: 'heefes@dsfs.com',
		gender: 'male',
		department: 'studia54',
	},
	{
		id: 2,
		name: 'Dima',
		surname: 'wowowood',
		email: 'dmitri@tttt.com',
		gender: 'male',
		department: 'studia54',
	},
	{
		id: 3,
		name: 'Michael',
		surname: 'Nights',
		email: 'nights@michael.com',
		gender: 'male',
		department: 'studia54',
	},
	{
		id: 4,
		name: 'Frank',
		surname: 'PostController',
		email: 'frank@ostController.ru',
		gender: 'male',
		department: 'architecture',
	},
	{
		id: 5,
		name: 'Tom',
		surname: 'Types',
		email: 'liza@types.com',
		gender: 'female',
		department: 'architecture',
	},
	{
		id: 6,
		name: 'Liza',
		surname: 'Types',
		email: 'liza@types.com',
		gender: 'female',
		department: 'architecture',
	},
];
